const products = [
  {
    img: "/Assets/Boats/aicha31/aicha1.jpg",
    slideImages: [
      { img: "/Assets/Boats/aicha31/aicha5.jpg" },
      { img: "/Assets/Boats/aicha31/aicha2.jpg" },
      { img: "/Assets/Boats/aicha31/aicha3.jpg" },
      { img: "/Assets/Boats/aicha31/aicha4.jpg" },
    ],
    name: "Aicha",
    slug: "aicha",
    category: "Luxury Boats",
    price: 375, // per hour, or product price
    bPrice:765,
    discount: 20, // percentage off
    rating: 4.5, // Average rating
    reviews: 120, // Number of reviews
    stock: 10, // Available stock
    description: "A luxury boat ideal for small groups, offering comfort and style for your outings on the water.",
    bedRooms: "1",
    washRooms: "1",
    maxPersons: 10,
  },
  {
    img: "/Assets/Boats/waverunner/waverunner.jpg",
    slideImages: [
      { img: "/Assets/Boats/waverunner/waverunner1.jpg" },
      { img: "/Assets/Boats/waverunner/waverunner2.jpg" },
      { img: "/Assets/Boats/waverunner/waverunner3.jpg" },
      { img: "/Assets/Boats/waverunner/waverunner4.jpg" },
    ],
    name: "Wave Runner",
    slug: "waverunner",
    category: "Luxury Boats",
    price: 600, 
    bPrice:900,
    discount: 15,
    rating: 4.7,
    reviews: 230,
    stock: 5,
    description: "A spacious and elegant boat with luxurious amenities for larger groups.",
    bedRooms: "2",
    washRooms: "2",
    maxPersons: 15,
  },
  {
    img: "/Assets/Boats/picasso/picasso1.jpg",
    slideImages: [
      { img: "/Assets/Boats/picasso/picasso1.jpg" },
      { img: "/Assets/Boats/picasso/picasso2.jpg" },
      { img: "/Assets/Boats/picasso/picasso3.jpg" },
      { img: "/Assets/Boats/picasso/picasso4.jpg" },
    ],
    name: "Picasso",
    slug: "picasso",
    category: "Luxury Boats",
    price: 700,
    bPrice:1200,
    discount: 25,
    rating: 4.8,
    reviews: 150,
    stock: 8,
    description: "A stunning 62-ft yacht designed for those seeking ultimate luxury and space.",
    bedRooms: "1",
    washRooms: "1",
    maxPersons: 25,
  },
  {
    img: "/Assets/Boats/ahira/ahira.jpg",
    slideImages: [
      { img: "/Assets/Boats/ahira/ahira1.jpg" },
      { img: "/Assets/Boats/ahira/ahira5.jpg" },
      { img: "/Assets/Boats/ahira/ahira3.jpg" },
      { img: "/Assets/Boats/ahira/ahira4.jpg" },
    ],
    name: "Ahira",
    slug: "ahira",
    category: "Luxury Boats",
    price: 800,
    bPrice:1300,
    discount: 20,
    rating: 4.9,
    reviews: 300,
    stock: 4,
    description: "An exquisite 84-ft yacht perfect for larger parties, with luxurious features and ample space.",
    bedRooms: "2",
    washRooms: "2",
    maxPersons: 30,
  },
  {
    img: "/Assets/Boats/jacuzzi/jacuzzi.jpg",
    slideImages: [
      { img: "/Assets/Boats/jacuzzi/jacuzzi5.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi2.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi3.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi4.jpg" },
    ],
    name: "Da Vinci",
    slug: "davinci",
    category: "Luxury Boats",
    price: 1400,
    bPrice:1600,
    discount: 20,
    rating: 5.0,
    reviews: 450,
    stock: 3,
    description: "The ultimate in luxury. An 88-ft yacht with 3 bedrooms, jacuzzi, and space for 35 guests.",
    bedRooms: "3",
    kitchen: "1",
    washRooms: "3",
    maxPersons: 35,
  },
];

export default products;
