const products = [
  {
    img: "/Assets/products/Aarch_Heel_Balm_1.jpg",
    slideImages: [
      { img: "/Assets/Boats/aicha31/aicha5.jpg" },
      { img: "/Assets/Boats/aicha31/aicha2.jpg" },
      { img: "/Assets/Boats/aicha31/aicha3.jpg" },
      { img: "/Assets/Boats/aicha31/aicha4.jpg" },
    ],
    name: "Aarch Heel Balm",
    slug: "aicha",
    category: "Luxury Boats",
    price: 375, // per hour, or product price
    bPrice:765,
    discount: 20, // percentage off
    rating: 4.5, // Average rating
    reviews: 120, // Number of reviews
    stock: 10, // Available stock
    description: "A luxury boat ideal for small groups, offering comfort and style for your outings on the water.",
    bedRooms: "1",
    washRooms: "1",
    maxPersons: 10,
  },
  {
    img: "/Assets/products/Acne_Star_Face_Gel.jpg",
    slideImages: [
      { img: "/Assets/Boats/waverunner/waverunner1.jpg" },
      { img: "/Assets/Boats/waverunner/waverunner2.jpg" },
      { img: "/Assets/Boats/waverunner/waverunner3.jpg" },
      { img: "/Assets/Boats/waverunner/waverunner4.jpg" },
    ],
    name: "Acne Star Face Gel",
    slug: "waverunner",
    category: "Luxury Boats",
    price: 600, 
    bPrice:900,
    discount: 15,
    rating: 4.7,
    reviews: 230,
    stock: 5,
    description: "A spacious and elegant boat with luxurious amenities for larger groups.",
    bedRooms: "2",
    washRooms: "2",
    maxPersons: 15,
  },
  {
    img: "/Assets/products/Adore_Petroleum_jelly_jar_3.jpg",
    slideImages: [
      { img: "/Assets/Boats/picasso/picasso1.jpg" },
      { img: "/Assets/Boats/picasso/picasso2.jpg" },
      { img: "/Assets/Boats/picasso/picasso3.jpg" },
      { img: "/Assets/Boats/picasso/picasso4.jpg" },
    ],
    name: "Adore Petroleum Jelly Jar",
    slug: "adore_pertroleum",
    category: "Luxury Boats",
    price: 700,
    bPrice:1200,
    discount: 25,
    rating: 4.8,
    reviews: 150,
    stock: 8,
    description: "A stunning 62-ft yacht designed for those seeking ultimate luxury and space.",
    bedRooms: "1",
    washRooms: "1",
    maxPersons: 25,
  },
  {
    img: "/Assets/products/AIRNERGY_Room_Spray.jpg",
    slideImages: [
      { img: "/Assets/Boats/ahira/ahira1.jpg" },
      { img: "/Assets/Boats/ahira/ahira5.jpg" },
      { img: "/Assets/Boats/ahira/ahira3.jpg" },
      { img: "/Assets/Boats/ahira/ahira4.jpg" },
    ],
    name: "Airnergy Room Spray",
    slug: "airnergy_room_spray",
    category: "Luxury Boats",
    price: 800,
    bPrice:1300,
    discount: 20,
    rating: 4.9,
    reviews: 300,
    stock: 4,
    description: "An exquisite 84-ft yacht perfect for larger parties, with luxurious features and ample space.",
    bedRooms: "2",
    washRooms: "2",
    maxPersons: 30,
  },
  {
    img: "/Assets/products/Al_Arabia_Attar.jpg",
    slideImages: [
      { img: "/Assets/Boats/jacuzzi/jacuzzi5.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi2.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi3.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi4.jpg" },
    ],
    name: "Al Arabia Attar",
    slug: "al_sarabia_attar",
    category: "Luxury Boats",
    price: 1400,
    bPrice:1600,
    discount: 20,
    rating: 5.0,
    reviews: 450,
    stock: 3,
    description: "The ultimate in luxury. An 88-ft yacht with 3 bedrooms, jacuzzi, and space for 35 guests.",
    bedRooms: "3",
    kitchen: "1",
    washRooms: "3",
    maxPersons: 35,
  },
  {
    img: "/Assets/products/Al_Arabia_Body_Spray_1.jpg",
    slideImages: [
      { img: "/Assets/Boats/jacuzzi/jacuzzi5.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi2.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi3.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi4.jpg" },
    ],
    name: "Al Arabia Body Spray",
    slug: "al_arabia_body_spray_1",
    category: "Luxury Boats",
    price: 1400,
    bPrice:1600,
    discount: 20,
    rating: 5.0,
    reviews: 450,
    stock: 3,
    description: "The ultimate in luxury. An 88-ft yacht with 3 bedrooms, jacuzzi, and space for 35 guests.",
    bedRooms: "3",
    kitchen: "1",
    washRooms: "3",
    maxPersons: 35,
  },
  {
    img: "/Assets/products/Al_Arabia_Body_Spray_2.jpg",
    slideImages: [
      { img: "/Assets/Boats/jacuzzi/jacuzzi5.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi2.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi3.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi4.jpg" },
    ],
    name: "Al Arabia Body Spray",
    slug: "al_arabia_body_spra_2",
    category: "Luxury Boats",
    price: 1400,
    bPrice:1600,
    discount: 20,
    rating: 5.0,
    reviews: 450,
    stock: 3,
    description: "The ultimate in luxury. An 88-ft yacht with 3 bedrooms, jacuzzi, and space for 35 guests.",
    bedRooms: "3",
    kitchen: "1",
    washRooms: "3",
    maxPersons: 35,
  },
  {
    img: "/Assets/products/Al_Arabia_Body_Spray.jpg",
    slideImages: [
      { img: "/Assets/Boats/jacuzzi/jacuzzi5.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi2.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi3.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi4.jpg" },
    ],
    name: "Da Vinci",
    slug: "davinci",
    category: "Luxury Boats",
    price: 1400,
    bPrice:1600,
    discount: 20,
    rating: 5.0,
    reviews: 450,
    stock: 3,
    description: "The ultimate in luxury. An 88-ft yacht with 3 bedrooms, jacuzzi, and space for 35 guests.",
    bedRooms: "3",
    kitchen: "1",
    washRooms: "3",
    maxPersons: 35,
  },
  {
    img: "/Assets/products/Apple_Hair_Colour_Jell.png",
    slideImages: [
      { img: "/Assets/Boats/jacuzzi/jacuzzi5.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi2.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi3.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi4.jpg" },
    ],
    name: "Apple Hair Colour Jell",
    slug: "apple_hair_colour_jell",
    category: "Luxury Boats",
    price: 1400,
    bPrice:1600,
    discount: 20,
    rating: 5.0,
    reviews: 450,
    stock: 3,
    description: "The ultimate in luxury. An 88-ft yacht with 3 bedrooms, jacuzzi, and space for 35 guests.",
    bedRooms: "3",
    kitchen: "1",
    washRooms: "3",
    maxPersons: 35,
  },
  {
    img: "/Assets/products/Axe_Body_Spray.jpg",
    slideImages: [
      { img: "/Assets/Boats/jacuzzi/jacuzzi5.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi2.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi3.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi4.jpg" },
    ],
    name: "Axe Body Spray",
    slug: "axe_body_spray",
    category: "Luxury Boats",
    price: 1400,
    bPrice:1600,
    discount: 20,
    rating: 5.0,
    reviews: 450,
    stock: 3,
    description: "The ultimate in luxury. An 88-ft yacht with 3 bedrooms, jacuzzi, and space for 35 guests.",
    bedRooms: "3",
    kitchen: "1",
    washRooms: "3",
    maxPersons: 35,
  },
  {
    img: "/Assets/products/BIO__AQUA_RICE_Jell.jpg",
    slideImages: [
      { img: "/Assets/Boats/jacuzzi/jacuzzi5.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi2.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi3.jpg" },
      { img: "/Assets/Boats/jacuzzi/jacuzzi4.jpg" },
    ],
    name: "BIO AQUA RICE Jell",
    slug: "bio__aqua_rice_jell",
    category: "Luxury Boats",
    price: 1400,
    bPrice:1600,
    discount: 20,
    rating: 5.0,
    reviews: 450,
    stock: 3,
    description: "The ultimate in luxury. An 88-ft yacht with 3 bedrooms, jacuzzi, and space for 35 guests.",
    bedRooms: "3",
    kitchen: "1",
    washRooms: "3",
    maxPersons: 35,
  },
];

export default products;
